#@ load("@ytt:template", "template")

#@ def usernames():
env_cf: ((((deploy-env))-cf-username))
env_cf_build_tasks: ((build-tasks-((deploy-env))-cf-username))
env_cf_redirects: ((redirects-cf-username))
env_cf_email: ((email-cf-username))
env_cf_editor: ((editor-((deploy-env))-cf-username))
#@ end

#@ def passwords():
env_cf: ((((deploy-env))-cf-password))
env_cf_build_tasks: ((build-tasks-((deploy-env))-cf-password))
env_cf_redirects: ((redirects-cf-password))
env_cf_email: ((email-cf-password))
env_cf_editor: ((editor-((deploy-env))-cf-password))
#@ end

#@ def spaces():
env_cf: ((deploy-env))
env_cf_build_tasks: build-tasks-((deploy-env))
env_cf_redirects: redirects
env_cf_email: email
env_cf_editor: editor-((deploy-env))
#@ end


#@data/values
---
env: null #! needs to be overridden

base: &base
  CF_API: https://api.fr.cloud.gov
  CF_ORG: gsa-18f-federalist
  CF_STACK: cflinuxfs4

#! this was close to being for-loopable but it's hard to make work for root level variables
env_cf:
  <<: *base
  CF_SPACE: #@ spaces()["env_cf"]
  CF_USERNAME: #@ usernames()["env_cf"]
  CF_PASSWORD: #@ passwords()["env_cf"]

env_cf_build_tasks:
  <<: *base
  CF_SPACE: #@ spaces()["env_cf_build_tasks"]
  CF_USERNAME: #@ usernames()["env_cf_build_tasks"]
  CF_PASSWORD: #@ passwords()["env_cf_build_tasks"]

env_cf_redirects:
  <<: *base
  CF_SPACE: #@ spaces()["env_cf_redirects"]
  CF_USERNAME: #@ usernames()["env_cf_redirects"]
  CF_PASSWORD: #@ passwords()["env_cf_redirects"]

env_cf_email:
  <<: *base
  CF_SPACE: #@ spaces()["env_cf_email"]
  CF_USERNAME: #@ usernames()["env_cf_email"]
  CF_PASSWORD: #@ passwords()["env_cf_email"]

env_cf_editor:
  <<: *base
  CF_SPACE: #@ spaces()["env_cf_editor"]
  CF_USERNAME: #@ usernames()["env_cf_editor"]
  CF_PASSWORD: #@ passwords()["env_cf_editor"]

release_steps:
  - get: general-task
  - get: pipeline-tasks
  - task: get-changelog-version
    image: general-task
    config:
      platform: linux
      inputs:
        - name: src
        - name: pipeline-tasks
      outputs:
        - name: src
      run:
        dir: src
        path: ../pipeline-tasks/scripts/get-changelog-version.sh
  - put: pages-release
    params:
      name: src/.git/ref
      tag: src/.git/ref
      body: src/releaselog.md
