#@data/values
---
env_cf:
  CF_API: https://api.fr.cloud.gov
  CF_USERNAME: ((((deploy-env))-cf-username))
  CF_PASSWORD: ((((deploy-env))-cf-password))
  CF_ORG: gsa-18f-federalist
  CF_SPACE: ((deploy-env))
  CF_STACK: cflinuxfs4

release_steps:
  - get: cf-image
  - task: get-changelog-version
    image: cf-image
    config:
      platform: linux
      inputs:
        - name: src
      outputs:
        - name: src
      run:
        dir: src
        path: ci/tasks/get-changelog-version.sh
  - put: pages-release
    params:
      name: src/.git/ref
      tag: src/.git/ref
      body: src/releaselog.md
